name: mainproject
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  http: ^1.3.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_core: ^3.13.0
  provider: ^6.1.5
  url_launcher: ^6.3.1
  intl: ^0.18.0
  percent_indicator: ^4.2.5
  upi_india: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  
  
flutter:
  uses-material-design: true
  
  
