// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaWzRsc7KxK_WWUH1_EJLKHCjDfVgwCbc',
    appId: '1:428986326639:web:2f3738f079067abbba379a',
    messagingSenderId: '428986326639',
    projectId: 'main-project-59878',
    authDomain: 'main-project-59878.firebaseapp.com',
    storageBucket: 'main-project-59878.firebasestorage.app',
    measurementId: 'G-77FHCK0GQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNePLz7biOSK83nvRGFgE7X9gv4CwYPGM',
    appId: '1:428986326639:android:4272c33a35a177a0ba379a',
    messagingSenderId: '428986326639',
    projectId: 'main-project-59878',
    storageBucket: 'main-project-59878.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ0w5VXhx5BSFZy5TZ9_duBnaz1f5f6ds',
    appId: '1:428986326639:ios:332cc031fe71bc26ba379a',
    messagingSenderId: '428986326639',
    projectId: 'main-project-59878',
    storageBucket: 'main-project-59878.firebasestorage.app',
    iosBundleId: 'com.example.mainproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ0w5VXhx5BSFZy5TZ9_duBnaz1f5f6ds',
    appId: '1:428986326639:ios:332cc031fe71bc26ba379a',
    messagingSenderId: '428986326639',
    projectId: 'main-project-59878',
    storageBucket: 'main-project-59878.firebasestorage.app',
    iosBundleId: 'com.example.mainproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaWzRsc7KxK_WWUH1_EJLKHCjDfVgwCbc',
    appId: '1:428986326639:web:6ff16c65763ce72cba379a',
    messagingSenderId: '428986326639',
    projectId: 'main-project-59878',
    authDomain: 'main-project-59878.firebaseapp.com',
    storageBucket: 'main-project-59878.firebasestorage.app',
    measurementId: 'G-ZG3M9NKCY3',
  );
}
